### ISSUE TITLE
Properly use the `/allow` command to set labels

### ISSUE THREAD

**Issue by gentlementlegen** [ubiquity-os-marketplace/command-start-stop#104]
/allow @gentlementlegen time

_Originally posted by @0x4007 in https://github.com/ubiquity/business-development/issues/102#issuecomment-2536031793_
            

## What happened

After using the `/allow` command, the user was still able to set all the other labels.

## What was expected

The user should only be able to set the labels that were allowed to their account.

## How to reproduce

- use an account that has permissions to set labels but is not a collaborator within the organization
- an admin uses the `/allow user time` command to only allow a user to set the time labels
- that user sets any other label using the UI
- notice that the bot does not revert the user's action

**Comment by 0x4007** [comment]
Only collaborators can set labels. The OS should undo a label set if that class of labels isn't white listed, or "allowed"

**Comment by gentlementlegen** [comment]
I am not sure to understand. Organization collaborators have no restrictions on label isn't it? I thought the scenario was on repositories where you all a user as a collaborator with `maintain` or `write` access?

**Comment by 0x4007** [comment]
It's impossible to set labels unless you're a collaborator under normal circumstances. 

The ONLY exception to this is if we make an issue template that allows a user to file an issue with pre set labels when submitting the issue. 

There is no UI for users to change labels unless they are a collaborator.
