### ISSUE TITLE
Registered Wallet Message

### ISSUE THREAD

**Issue by 0x4007** [ubiquity-os-marketplace/command-start-stop#23]
Draw attention to the user to register their wallet. The syntax is as follows:
```
> [!WARNING]
> Register your wallet to be eligible for rewards. 
```

I also made minor adjustments to the tips section.

---

<samp>
<table>
<tr><td>Deadline</td><td>Tue, Aug 13, 10:17 PM UTC</td></tr>
<tr><td>Beneficiary</td><td>

> [!WARNING]
> Register your wallet to be eligible for rewards. 

</td></tr>
</table>
</samp>
  

###### Tips:
- Use `/wallet 0x0000...0000` if you want to update your registered wallet address.
- Be sure to open a draft pull request as soon as possible to communicate updates on your progress.
- Be sure to provide timely updates to us when requested, or you will be automatically unassigned from the task.

---

_Originally posted by @ubqbot[bot] in https://github.com/ubq-testing/bot-ai/issues/51#issuecomment-2287154227_

**Comment by gentlementlegen** [comment]
Would this be only in the case where we allow users to start without a wallet? Because when the wallet is required it is not possible to start a task thus this message won't appear.

**Comment by 0x4007** [comment]
> Would this be only in the case where we allow users to start without a wallet?

Yes

**Comment by gentlementlegen** [comment]
I believe it is because every thrown error posts a message, I saw this change a few weeks back in that plugin.

**Comment by 0x4007** [comment]
> I believe it is because every thrown error posts a message, I saw this change a few weeks back in that plugin.

On one hand this makes sense, but on the other its too verbose. Maybe this error should actually be using the debug method instead of error method on our logger? Then it will not normally show. We can consider changing the environment variable to enable debug messages to show on the dev instance, but the production instance should only show errors probably.

**Comment by gentlementlegen** [comment]
I guess we should selectively post the errors we want to display, because some we might want to post the message and other silently fail. Also now the cloudflare logs have retention (up to 200 000 messages on free tier I think) so errors can be easily found without needed to store them on Supabase like it was done before.
