### ISSUE TITLE
Check deadline displayed for 1h tasks

### ISSUE THREAD

**Issue by gentlementlegen** [ubiquity-os-marketplace/command-start-stop#38]
> I didn't change the code logic (I think) to get the deadline

That'll be my mistake then my bad. My timezone is UTC+00 which I'm sure is the same as the reminder, do you think you could add a `+ 1` so that it's achievable to complete a 1hr task within the deadline?

> And I think completed should be PR opening + ready to review, being merged in 1 hours sounds unrealistic.

Agreed lol. And with issue/PR activity bumping it forward technically it's not a strict deadline either so calculating a bonus/negative based on the deadline seems like it will be a difficult task actually.

_Originally posted by @Keyrxng in https://github.com/ubiquibot/command-start-stop/issues/24#issuecomment-2333833887_

**Comment by gentlementlegen** [comment]
@Keyrxng I tested this again and it seemed to work fine, when everything was compared in UTC. Is is still happening to you?

**Comment by Keyrxng** [comment]
Yeah it appeared so until just now. 

I realize actually that if I change my clock to `UTC` and not `UTC+00:00 Edinburgh, London` (which I believed to be the same thing until right now, which GPT4 also told me it was) my computer clock jumps back 1hr. But my time zone is `UTC+00:00` so I guess this is my user error in telling the time? lmao turns only my UTC+00:00 is the only one which is forward one hour from the others so yeah my bad I guess  🤣

![image](https://github.com/user-attachments/assets/6fd312ea-0e01-4b1c-95f1-1973a45677aa)

**Comment by gentlementlegen** [comment]
@Keyrxng interesting, you don't have summer / winter hour in your region? Closing this as it is working fine.
