### ISSUE TITLE
Do not post all the errors to the GitHub issue

### ISSUE THREAD

**Issue by gentlementlegen** [ubiquity-os-marketplace/command-start-stop#60]
```diff
! No labels are set.
```

_Originally posted by @ubiquity-os[bot] in https://github.com/ubiquity-os-marketplace/command-start-stop/issues/23#issuecomment-2376236748_
            

This should not be posted to the issue.

**Comment by 0x4007** [comment]
It would be nice to batch rolling changes because even one hour seems like too much for some of these small changes. Maybe we can make `Time: <5 Minutes` but that seems silly. I wonder what is a better process.

**Comment by gentlementlegen** [comment]
Well it depends, maybe we could have a base fixed priced for under one hour? Maybe we could add 30 minutes? But technically doing the changes + testing on your own org for QA + writing unit test could take at least 45 minutes even for such a simple task.

**Comment by 0x4007** [comment]
>  Well it depends, maybe we could have a base fixed priced for under one hour? Maybe we could add 30 minutes? But technically doing the changes + testing on your own org for QA + writing unit test could take at least 45 minutes even for such a simple task.

I think makes more sense to batch these same types of changes. There's a fixed setup and breakdown time to get into this type of simple project.
