### ISSUE TITLE
Task Limit Improvements

### ISSUE THREAD

**Issue by 0x4007** [ubiquity-os-marketplace/command-start-stop#64]
This needs to:

1. Change to warning syntax vs diff syntax
2. Link all the issues I'm currently assigned to in a comment so I can unassign myself or close them out. 
3. Only check assigned issues within the network, but this should be configurable to either be just within the repo, org, or network

---

```diff
! You have reached your max task limit. Please close out some tasks before assigning new ones.
```

_Originally posted by @ubiquity-os[bot] in https://github.com/ubiquity/work.ubq.fi/issues/120#issuecomment-2404264757_
            

>[!WARNING]
> You have reached your max task limit. Please close out some tasks before assigning new ones.

**Comment by 0x4007** [comment]
```
curl -H "Authorization: bearer $GITHUB_TOKEN" -X POST -d @- https://api.github.com/graphql <<EOF | jq '.data.search.nodes[].url'
{
  "query": "query AssignedIssues { search(query: \"assignee:0x4007 is:open is:issue\", type: ISSUE, first: 100) { nodes { ... on Issue { url } } } }"
}
```

Returns URLs. 

---

I'm not sure if it asks the GitHub API for any assigned issue but thats dumb, it should be only within the network (devpool directory) or at the very least the same org.

**Comment by ariesgun** [comment]
> AssignedIssues

@0x4007, Is it possible to check https://raw.githubusercontent.com/ubiquity/devpool-directory/refs/heads/development/devpool-issues.json for assigness?
It seems that the json file does not contain issues that have been assigned.

**Comment by 0x4007** [comment]
Then you query the API for those issue node ids if they are assigned

**Comment by 0x4007** [comment]
This counts against my limit and its archived so I cant really do much about it. Once we only count against tasks in our network this problem will be resolved: https://github.com/ubiquity/uad-ui-archived/issues/15

**Comment by rndquu** [comment]
@0x4007 Could you assign @ariesgun (related [comment](https://t.me/UbiquityDevPool/2885))? Only org owners can set github issue assignees.

**Comment by gentlementlegen** [comment]
@whilefoo the comment generation failed due to an invalid signature: https://github.com/ubiquity-os-marketplace/text-conversation-rewards/actions/runs/11735148935/job/32692347908

However the signature for dev bot seems to have been sent properly, any ideas?

**Comment by whilefoo** [comment]
> @whilefoo the comment generation failed due to an invalid signature: https://github.com/ubiquity-os-marketplace/text-conversation-rewards/actions/runs/11735148935/job/32692347908
> 
> However the signature for dev bot seems to have been sent properly, any ideas?

refer to https://github.com/ubiquity-os/ubiquity-os-kernel/issues/194
