### ISSUE TITLE
Change `search` queries to GraphQl to avoid permission issues

### ISSUE THREAD

**Issue by gentlementlegen** [ubiquity-os-marketplace/command-start-stop#70]
It is still weird to me that the user privacy affects a search because the profile is public. Can we consider using GQL with issues search instead of the search API? Something like
```gql
query($organization: String!, $author: String!) {
  organization(login: $organization) {
    repositories(first: 100) {
      nodes {
        issues(first: 100, states: OPEN, filterBy: {createdBy: $author}) {
          nodes {
            title
            url
            createdAt
          }
        }
      }
    }
  }
}
```

with

```json
{
  "organization": "ubiquity",
  "author": "sshivaditya2019"
}
```

would achieve the same result. I don't know if that would resolve the issue but it's worth a try.

_Originally posted by @gentlementlegen in https://github.com/ubiquity/work.ubq.fi/issues/119#issuecomment-2440640493_

**Comment by 0x4007** [comment]
Somebody should test and see if this works before we fund it.

**Comment by gentlementlegen** [comment]
@0x4007 I spent quite some time on this. It seems to work ok but it is awfully slow at the moment, I'll try to see if there is a better way.

**Comment by gentlementlegen** [comment]
@0x4007 I managed to make it faster but it takes still something like 5 to 10 seconds depending on the org (`ubiquity` for example has tons of PRs). GitHub search is obviously using caching and indexing to provide near instant results. Maybe we could have this logic as a backup when the search fails?

**Comment by 0x4007** [comment]
Seamless fallback seems like a reasonable solution.

**Comment by gentlementlegen** [comment]
@Keyrxng We might want to improve that message, maybe not even post it because I don't think it's relevant to users.

**Comment by Keyrxng** [comment]
I recently added logic to comment any [`status !== 200`](https://github.com/ubiquity-os-marketplace/ubiquity-os-kernel-telegram/blob/103bd38bc676e76d540f566cbe37503cfac79d79/src/handlers/workflow-proxy.ts#L33) for workflows during debugging it's handy but needs tweaked for sure.

**Comment by gentlementlegen** [comment]
I think room creation failure is important to understand that it tried to open it but failed; closing errors might be silent. We always have the logs in the Actions and Cloudflare logs if needed. But yes we should discuss these in details. We can keep the closing error but we need a prettier message at least.
