### ISSUE TITLE
User un-assign should close its linked pull-requests

### ISSUE THREAD

**Issue by gentlementlegen** [ubiquity-os-marketplace/command-start-stop#74]
Disqualify needs to close the pull

_Originally posted by @0x4007 in https://github.com/ubiquity-os-marketplace/daemon-merging/issues/22#issuecomment-2452913872_

**Comment by gentlementlegen** [comment]
@0x4007 The root of this problem was caused by 2 factors:
- the value checked for the assigned person that got un-assigned was wrong
- the event gets skipped because the sender is a bot (disqualifier plugin). We should add a `skipBotEvents: false` to our configuration.

**Comment by gentlementlegen** [comment]
I realized this has a side effect when considering the actions of the bot: since the bot assigns the user, it creates a assign even resulting in double posting the start comment. I think the logic should be centralized so that this doesn't happen.

**Comment by gentlementlegen** [comment]
@0x4007 shouls this be priced?

**Comment by 0x4007** [comment]
I suppose generally speaking fixes for regressions shouldn't be rewarded to the code owners
