### ISSUE TITLE
Assigned issue URLs are not displayed on reaching max task limit 

### ISSUE THREAD

**Issue by rndquu** [ubiquity-os-marketplace/command-start-stop#96]
Check [this](https://github.com/ubiquity-os-marketplace/text-conversation-rewards/issues/185#issuecomment-2492223252) comment which displays a warning that max task limit is reached.

It should also display URLs to already assigned github issues ([example](https://github.com/ubiquity-os/ubiquity-os-plugin-installer/issues/22#issuecomment-2494976657)).

There seems to be a bug since this logic is [already implemented](https://github.com/ubiquity-os-marketplace/command-start-stop/blob/ab45541cf62e69ea3996120068f1b6b15fc42f86/src/handlers/shared/start.ts#L105).

What should be done:
1. Fix the bug
2. Write a unit test for the feature

Original [comment](https://github.com/ubiquity-os-marketplace/text-conversation-rewards/issues/185#issuecomment-2492919269)

**Comment by rndquu** [comment]
> Why is the author not assigned to the issues although he is working on those issues? Is this typical?

Because the author didn't call the `/start` command. As far as I remember when PR is opened an issue should be assigned automatically, not sure if this feature exists or that's a bug (@gentlementlegen help).

> What is the expected result in this scenario? Should we assign the issue or not?

I don't fully understand the question. [This](https://github.com/ubiquity-os-marketplace/text-conversation-rewards/issues/185#issuecomment-2492223252) warning was triggered because max task limit was reached. The only thing left is to find out how assigned issues were calculated and attach missing URLs to PRs.

> One possible way to solve it is to check the PR body and parse the "Resolve #XXX" text to retrieve the issues someone is working on. It is going to make to code check quite complicated. What do you think of this solution?

Why do we need to parse comments? Can't we use already [implemented](https://github.com/ubiquity-os-marketplace/command-start-stop/blob/70a9619d496a175a09c6a3c4de4d7a84da1da919/src/utils/get-linked-prs.ts) solutions?

**Comment by gentlementlegen** [comment]
@rndquu yes on pull-request linking if the task is not assign it should assign you. The reason why it has not been working is that when a profile is private the plugin fails to retrieve the pull-requests of a user due to privacy settings.

**Comment by rndquu** [comment]
> > I don't fully understand the question. [This](https://github.com/ubiquity-os-marketplace/text-conversation-rewards/issues/185#issuecomment-2492223252) warning was triggered because max task limit was reached. The only thing left is to find out how assigned issues were calculated and attach missing URLs to PRs.
> 
> The author is assigned 0 issue , but he has created 5 PRs. That's why when he tried to call the `/start` command, it said max task limit was reached (abs(0 issue - 5 open PRs) > limit 2). The question is should it returns 'max task limit' or should it assign the issue?
> 
> ```
>   // check for max and enforce max
>   if (Math.abs(assignedIssues.length - openedPullRequests.length) >= limit) {
> ```

I suppose right now the logic is correct. If user has 0 assigned issues and 5 opened PRs then user should not be assigned. He can simply close PRs and try to `/start` again.

**Comment by 0x4007** [comment]
@gentlementlegen

**Comment by gentlementlegen** [comment]
Can be open again if needed.
